#Version Number
version: 20200812

#Site Info
title: Gizmokid2005.com
email: gizmokid2005@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Organized Chaos!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gizmokid2005.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Gizmokid2005
github_username:  Gizmokid2005
github:
  repository_name: Gizmokid2005/gizmokid2005.com
  project_tagline: This is my website
  owner_name: Gizmokid2005
  owner_url: https://gizmokid2005.com

defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename/
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll_inline_highlight
  - jekyll-minifier
  - jekyll-redirect-from
include: ['_pages','.htaccess']
#exclude: ['updatesite.sh']
exclude:
  - updatesite.sh
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
strict_front_matter: true
keep_files:
  - icon
  - stats
  - awstatsicons
  - awstats-icon
  - temp
  - video
  - keybase.txt

permalink: /:year/:month/:title
excerpt_separator: <!--more-->
paginate: 15
jekyll-minifier:
  compress_javascript: false
#  compress_css: false
#  exclude: ['jquery-3.7.0.slim.min.js','bootstrap.bundle.js','bootstrap.bundle.js.map','bootstrap.bundle.min.js','bootstrap.bundle.min.js.map','respond.js']
  exclude:
  - jquery-3.7.0.slim.min.js
  - bootstrap.bundle.js
  - bootstrap.bundle.js.map
  - bootstrap.bundle.min.js
  - bootstrap.bundle.min.js.map
  - respond.js
  uglifier_args:
    harmony: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
