source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem 'jekyll', '~> 4.0'
gem "cssminify2", :git => 'https://github.com/bbbenji/cssminify'

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed" #, "~> 0.6"
  gem "jekyll-import"
  gem "jekyll-seo-tag"
  gem "jekyll-paginate"
  # gem "jekyll_inline_highlight", github: "Gizmokid2005/inline_highlight"
  gem "jekyll-minifier"
  gem "jekyll-redirect-from"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby] if Gem.win_platform?

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1" if Gem.win_platform?


gem "webrick", "~> 1.7"
